### ISSUE TITLE
why use createMnemonic get 24 word

### ISSUE THREAD

**Issue by zuoliang0** [NovaCrypto/BIP39#24]
when i use 
f=fc534ee49d7d44f7942996f13ba11372f939e5fcc02dd89eb4fdd23e4dcdb134
```
 new MnemonicGenerator(wordList)
                .createMnemonic(f, sb::append);
```
i got "wisdom omit rice depend stairs knock expose crazy van tackle dynamic tourist near very vessel aisle sudden volcano disorder piece tooth traffic shadow mother" total 24 words,

i wannn 12 word. like METAMASK  

thank you

**Comment by nym-zone** [comment]
@zuoliang0 wrote:

>when i use
>f=fc534ee49d7d44f7942996f13ba11372f939e5fcc02dd89eb4fdd23e4dcdb134
>
>```
> new MnemonicGenerator(wordList)
>                .createMnemonic(f, sb::append);
>```
>
>i got "wisdom omit rice depend stairs knock expose crazy van tackle dynamic tourist near very vessel aisle sudden volcano disorder piece tooth traffic shadow mother" total 24 words,
>
>i wannn 12 word. like METAMASK
>
>thank you

Well, let’s see what this does at [MnemonicGenerator.java:49](https://github.com/NovaCrypto/BIP39/blob/8d9c542bcb864a8e0150518d74e5835477797f12/src/main/java/io/github/novacrypto/bip39/MnemonicGenerator.java#L49):

```
    /**
     * Create a mnemonic from the word list given the entropy.
     *
     * @param entropyHex 128-256 bits of hex entropy, number of bits must also be divisible by 32
     * @param target     Where to write the mnemonic to
     */
    public void createMnemonic(
            final CharSequence entropyHex,
            final Target target) {
        final int length = entropyHex.length();
        if (length % 2 == 1)
            throw new RuntimeException("Length of hex chars must be divisible by 2");
        final byte[] entropy = new byte[length / 2];
```

You gave it 256 bits of a value which is supposed to be secret, but you have now revealed in public:

```
$ echo -n fc534ee49d7d44f7942996f13ba11372f939e5fcc02dd89eb4fdd23e4dcdb134 | wc -c
64
```

That will generate a 24-word mnemonic, according to [BIP 39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki).  What did you expect?  Give it the number of bits which will generate the word-length you desire.

----

@westonal, I suggest closing as NOTABUG.  (I am not affiliated with this project.)

**Comment by westonal** [comment]
Sorry I didn't see this.

Please see: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

The length of your input entropy dictates the number of words output:

```
CS = ENT / 32
MS = (ENT + CS) / 11

|  ENT  | CS | ENT+CS |  MS  |
+-------+----+--------+------+
|  128  |  4 |   132  |  12  |
|  160  |  5 |   165  |  15  |
|  192  |  6 |   198  |  18  |
|  224  |  7 |   231  |  21  |
|  256  |  8 |   264  |  24  |
```

ENT is input length, MS is word count. 

For 12 words, you need half the length of input. You've supplied 64 hex, so 256 bits, which checks out on the table.

**Comment by westonal** [comment]
I should add, there may be a method METAMASK uses to get from 256 to 128 first, but that would be outside the scope of this library as it's not described in BIP0039.

For example https://iancoleman.io/bip39/ lets you enter entropy, and then separately choose the word length. How this is achieved isn't clear or defined in BIP0039.

**Comment by nym-zone** [comment]
@westonal:

>I should add, there may be a method METAMASK uses to get from 256 to 128 first, but that would be outside the scope of this library as it's not described in BIP0039.

I have no idea what METAMASK is, nor do I care to search.

>For example https://iancoleman.io/bip39/ lets you enter entropy, and then separately choose the word length. How this is achieved isn't clear or defined in BIP0039.

By the pigeonhole principle, of course, it is mathematically, arithmetically impossible to fit 256 bits into 128 bits; and likewise, it is impossible to fit 256 bits into a 12-word mnemonic made with a 2048-word list.  Therefore, either such implementations are using non-BIP39 lists of differing lengths, or they are throwing away entropy.  Without looking, I *suspect* what is being done is to hash input entropy, then truncate the hash to the input length needed for the requested output length.

User-provided “entropy” is usually bad, anyway; so perhaps some of these systems are hashing user input with other sources through some sort of key-stretching KDF.

Yes, this is all *far* outside the scope of BIP 39.  In my opinion, it is also outside the scope of sanity.

**Comment by zuoliang0** [comment]
thank you for every one，
and METAMASK  is google chrome extension，https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=zh-CN

it use for browser  generate and management the ethereum account。

**Comment by westonal** [comment]
np, thanks for checking out my library
