### ISSUE TITLE
Misleading PRF name gives code review heart attack

### ISSUE THREAD

**Issue by nym-zone** [NovaCrypto/BIP39#25]
Quoting [BIP 39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki):

>HMAC-SHA512 is used as the pseudo-random function.

Quoting [SeedCalculator.java:38](https://github.com/NovaCrypto/BIP39/blob/05286d9e85a25ffad1cb0cfef8ed221dcb87729f/src/main/java/io/github/novacrypto/bip39/SeedCalculator.java#L38):

```
    private final PBKDF2WithHmacSHA256 hashAlgorithm;

    public SeedCalculator(PBKDF2WithHmacSHA256 hashAlgorithm) {
        this.hashAlgorithm = hashAlgorithm;
}
```

On a two-minute glance through the code, I had an understandable reaction.  Then, I reached for `grep` and found these:

[JavaxPBKDF2WithHmacSHA256.java:36](https://github.com/NovaCrypto/BIP39/blob/f48c9d115bf1869064b8288a46c10073488a62e2/src/main/java/io/github/novacrypto/bip39/JavaxPBKDF2WithHmacSHA256.java#L36):

```
public enum JavaxPBKDF2WithHmacSHA256 implements PBKDF2WithHmacSHA256 {
    INSTANCE;

    private SecretKeyFactory skf = getPbkdf2WithHmacSHA512();

    @Override
    public byte[] hash(char[] chars, byte[] salt) {
        final PBEKeySpec spec = new PBEKeySpec(chars, salt, 2048, 512);
```

[SpongyCastlePBKDF2WithHmacSHA256.java:32](https://github.com/NovaCrypto/BIP39/blob/f48c9d115bf1869064b8288a46c10073488a62e2/src/main/java/io/github/novacrypto/bip39/SpongyCastlePBKDF2WithHmacSHA256.java#L32):

```
public enum SpongyCastlePBKDF2WithHmacSHA256 implements PBKDF2WithHmacSHA256 {
    INSTANCE;

    @Override
    public byte[] hash(char[] chars, byte[] salt) {
        PKCS5S2ParametersGenerator generator = new PKCS5S2ParametersGenerator(new SHA512Digest());
```

I am still not sure how it all fits together.  But I suggest it may be kinder to code reviewers to not misidentify the PRF in variable names.  Or perhaps you wish to test whether readers be paying attention? [g]

**Comment by westonal** [comment]
Yes, it was a test! you passed!

**Comment by westonal** [comment]
Note that this repo has many many test cases and if I actually used 256 by mistake they would all fail. But I will, of course, be fixing the names. Good spot, thanks!

**Comment by nym-zone** [comment]
@westonal:

>Note that this repo has many many test cases and if I actually used 256 by mistake they would all fail. But I will, of course, be fixing the names. Good spot, thanks!

You’re welcome.

I saw the tests directories, but didn’t look into them.  And I am only glancing through, reading the code; I don’t have Java installed on this system.  Thus, the initial version of my report explicitly inquired whether you were using the [reference implementation’s vectors](https://github.com/trezor/python-mnemonic/blob/master/vectors.json).  Then, I reached for `grep`.

I think I learned a lesson here:  To avoid embarrassing meta-mistakes, always `grep`!

(P.S., I see you also have test vectors I don’t in my implementation; I will look into cribbing those from upstream.  I’d been wanting some non-English language test vectors.  easyseed runs basic self-tests at every runtime; and I am greedy for more tests.)

**Comment by westonal** [comment]
English and Japanese are from: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki test vector links at bottom, other ones I manually constructed from https://iancoleman.io/bip39/

So don't immediately assume an issue with your code if it does fail, a copy paste error is ever so slightly possible.

**Comment by nym-zone** [comment]
Of course!  The BIP 39 document is how I found my existing English test vectors (and also, duh, the specification I am implementing).  I don’t know how I overlooked the link to the Japanese vectors.  My brain must have been out to lunch.

I think I will also copypaste the others from iancoleman’s repo.

Thank you for the tip (as to Japanese, really, the correction).
