### ISSUE TITLE
How to get private key in the project?

### ISSUE THREAD

**Issue by CokeBear666** [NovaCrypto/BIP39#29]
How to get private key in the project?

**Comment by westonal** [comment]
Hey, good question, take a look here: https://medium.com/@_west_on/quick-guide-to-generating-addresses-in-novacrypto-e0cb13ff612

In this BIP39 project, it's just about generating a seed. For generating addresses we have [BIP32](https://github.com/NovaCrypto/BIP32) library, that's not set up easily yet for extracting the private key, but it is part of the `extendedKeyByteArray`.
