### ISSUE TITLE
Missing Sha256 class

### ISSUE THREAD

**Issue by st0rmtroop3r** [NovaCrypto/BIP39#37]
I tried the example "Using a StringBuilder" and got "Exception in thread "main" java.lang.NoClassDefFoundError: io/github/novacrypto/hashing/Sha256".
MnemonicGenerator has an import of io.github.novacrypto.hashing.Sha256, but there is no such package as io.github.novacrypto.hashing.

**Comment by st0rmtroop3r** [comment]
Sorry for duplicating the issue. I found the solution here https://github.com/NovaCrypto/BIP39/issues/36
I created gradle project and it works. But how could I use this lib in non maven and non gradle project?

**Comment by westonal** [comment]
> But how could I use this lib in non maven and non gradle project?

So sorry for the delay. You would have to download the jars that it uses. If you look at this project's [`build.gradle`](https://github.com/NovaCrypto/BIP39/blob/master/build.gradle#L80), you can see what it uses.

```
    compile 'com.madgag.spongycastle:core:1.58.0.0@jar'
    compile 'io.github.novacrypto:SHA256:2018.10.06@jar'
    compile 'io.github.novacrypto:ToRuntime:2018.10.06@jar'
```
